name: upload my image to DockerHub
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build . --tag ${{ secrets.DOCKER_USERNAME }}/collection2025:latest

      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/collection2025:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: stop old container
        run: sudo docker stop collection2025
      - name: delete old container
        run: sudo docker rm -f collection2025
      - name: pull image from docker
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/collection2025:latest
      - name: run docker container
        run: sudo docker run --name collection2025 -d -p 80:3000 -e MONGODB_CONNECTION_STRING="${{ secrets.MONGODB_CONNECTION_STRING }}" ${{ secrets.DOCKER_USERNAME }}/collection2025
      # - name: Deploy app
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USER }}
      #     key: ${{ secrets.PRIVATE_KEY }}
      #     port: ${{ secrets.PORT }}
      #     script: |
      #       sudo docker stop collection2025
      #       sudo docker rm collection2025
      #       sudo docker rmi yairf11/collection2025
      #       sudo docker pull yairf11/collection2025
      #       sudo docker run --name collection2025 -d -p 80:3000 -e MONGODB_CONNECTION_STRING="${{ secrets.MONGODB_CONNECTION_STRING }}" yairf11/collection2025
